/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// AdministratorRoleRights : Administrator role right details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AdministratorRoleRights {
    /// Right to create new administrator roles.
    #[serde(rename = "canCreateNewAdministratorRoles", skip_serializing_if = "Option::is_none")]
    pub can_create_new_administrator_roles: Option<bool>,
    /// Right to delete administrator roles.
    #[serde(rename = "canDeleteAdministratorRoles", skip_serializing_if = "Option::is_none")]
    pub can_delete_administrator_roles: Option<bool>,
    /// Right to edit administrator roles.
    #[serde(rename = "canEditAdministratorRoleProperties", skip_serializing_if = "Option::is_none")]
    pub can_edit_administrator_role_properties: Option<bool>,
    /// Right to view administrator roles.
    #[serde(rename = "canViewAdministratorRoles", skip_serializing_if = "Option::is_none")]
    pub can_view_administrator_roles: Option<bool>,
}

impl AdministratorRoleRights {
    /// Administrator role right details.
    pub fn new() -> AdministratorRoleRights {
        AdministratorRoleRights {
            can_create_new_administrator_roles: None,
            can_delete_administrator_roles: None,
            can_edit_administrator_role_properties: None,
            can_view_administrator_roles: None,
        }
    }
}


