/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// AgentActivationInformation : Agent activation information.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct AgentActivationInformation {
    /// Activation URL.
    #[serde(rename = "activationURL", skip_serializing_if = "Option::is_none")]
    pub activation_url: Option<String>,
    /// Activation token.
    #[serde(rename = "activationToken", skip_serializing_if = "Option::is_none")]
    pub activation_token: Option<String>,
}

impl AgentActivationInformation {
    /// Agent activation information.
    pub fn new() -> AgentActivationInformation {
        AgentActivationInformation {
            activation_url: None,
            activation_token: None,
        }
    }
}
