/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ApplicationControlGlobalRule : Rule details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApplicationControlGlobalRule {
    /// SHA-256 hash of the executable named in the rule. Searchable as String.
    #[serde(rename = "sha256", skip_serializing_if = "Option::is_none")]
    pub sha256: Option<String>,
    /// Description of the rule. Searchable as String.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Action to take when a user attempts to launch the executable named in the rule. Searchable as Choice.
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Action>,
    /// ID of the last administrator to update the rule. Searchable as Numeric.
    #[serde(rename = "lastUpdatedAdministrator", skip_serializing_if = "Option::is_none")]
    pub last_updated_administrator: Option<i32>,
    /// Timestamp of the last rule modification, in milliseconds since epoch. Searchable as Date.
    #[serde(rename = "lastUpdated", skip_serializing_if = "Option::is_none")]
    pub last_updated: Option<i64>,
    /// ID of the application control rule. Searchable as ID.
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<i64>,
}

impl ApplicationControlGlobalRule {
    /// Rule details.
    pub fn new() -> ApplicationControlGlobalRule {
        ApplicationControlGlobalRule {
            sha256: None,
            description: None,
            action: None,
            last_updated_administrator: None,
            last_updated: None,
            ID: None,
        }
    }
}

/// Action to take when a user attempts to launch the executable named in the rule. Searchable as Choice.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "block")]
    Block,
}

