/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// ComputerFilter : Details of a computer filter. A computer filter identifies the computers that certain types of scheduled tasks act on.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputerFilter {
    /// The type of computer filter.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
    /// Computer ID for filter type: computer.
    #[serde(rename = "computerID", skip_serializing_if = "Option::is_none")]
    pub computer_id: Option<i32>,
    /// Computer Group ID for filter type: computers-in-group or computers-in-group-or-subgroup.
    #[serde(rename = "computerGroupID", skip_serializing_if = "Option::is_none")]
    pub computer_group_id: Option<i32>,
    /// Policy ID for filter type: computers-using-policy or computers-using-policy-or-subpolicy.
    #[serde(rename = "policyID", skip_serializing_if = "Option::is_none")]
    pub policy_id: Option<i32>,
    /// Smart Folder ID for filter type: computers-in-smart-folder.
    #[serde(rename = "smartFolderID", skip_serializing_if = "Option::is_none")]
    pub smart_folder_id: Option<i64>,
}

impl ComputerFilter {
    /// Details of a computer filter. A computer filter identifies the computers that certain types of scheduled tasks act on.
    pub fn new() -> ComputerFilter {
        ComputerFilter {
            _type: None,
            computer_id: None,
            computer_group_id: None,
            policy_id: None,
            smart_folder_id: None,
        }
    }
}

/// The type of computer filter.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "computer")]
    Computer,
    #[serde(rename = "all-computers")]
    AllComputers,
    #[serde(rename = "computers-in-group")]
    ComputersInGroup,
    #[serde(rename = "computers-in-group-or-subgroup")]
    ComputersInGroupOrSubgroup,
    #[serde(rename = "computers-using-policy")]
    ComputersUsingPolicy,
    #[serde(rename = "computers-using-policy-or-subpolicy")]
    ComputersUsingPolicyOrSubpolicy,
    #[serde(rename = "computers-in-smart-folder")]
    ComputersInSmartFolder,
}
