/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// ComputerTasks : Computer task details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputerTasks {
    /// Agent tasks. Searchable as String.
    #[serde(rename = "agentTasks", skip_serializing_if = "Option::is_none")]
    pub agent_tasks: Option<Vec<String>>,
    /// Appliance tasks. Searchable as String.
    #[serde(rename = "applianceTasks", skip_serializing_if = "Option::is_none")]
    pub appliance_tasks: Option<Vec<String>>,
}

impl ComputerTasks {
    /// Computer task details.
    pub fn new() -> ComputerTasks {
        ComputerTasks {
            agent_tasks: None,
            appliance_tasks: None,
        }
    }
}


