/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// ComputerModuleStatus : Computer Module status details.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct ComputerModuleStatus {
    /// Agent status.
    #[serde(rename = "agentStatus", skip_serializing_if = "Option::is_none")]
    pub agent_status: Option<AgentStatus>,
    /// Agent status message.
    #[serde(rename = "agentStatusMessage", skip_serializing_if = "Option::is_none")]
    pub agent_status_message: Option<String>,
    /// Appliance status.
    #[serde(rename = "applianceStatus", skip_serializing_if = "Option::is_none")]
    pub appliance_status: Option<ApplianceStatus>,
    /// Appliance status message.
    #[serde(
        rename = "applianceStatusMessage",
        skip_serializing_if = "Option::is_none"
    )]
    pub appliance_status_message: Option<String>,
}

impl ComputerModuleStatus {
    /// Computer Module status details.
    pub fn new() -> ComputerModuleStatus {
        ComputerModuleStatus {
            agent_status: None,
            agent_status_message: None,
            appliance_status: None,
            appliance_status_message: None,
        }
    }
}

/// Agent status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AgentStatus {
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "not-supported")]
    NotSupported,
}
/// Appliance status.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ApplianceStatus {
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "warning")]
    Warning,
    #[serde(rename = "error")]
    Error,
    #[serde(rename = "not-supported")]
    NotSupported,
}
