/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// DirectoryList : Collection of directories.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct DirectoryList {
    /// Name of the directory list. Searchable as String.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description of the directory list. Searchable as String.
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// List of directory paths. Windows directories need to end in a backslash (\\). Asterisk (*) is a wildcard character.
    #[serde(rename = "items", skip_serializing_if = "Option::is_none")]
    pub items: Option<Vec<String>>,
    /// ID of the directory list. This number is set automatically. Searchable as ID.
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<i32>,
}

impl DirectoryList {
    /// Collection of directories.
    pub fn new() -> DirectoryList {
        DirectoryList {
            name: None,
            description: None,
            items: None,
            ID: None,
        }
    }
}


