/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// FirewallComputerExtension : Computer-level configuration for the Firewall module. Null for tenants for whom Firewall is hidden.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct FirewallComputerExtension {
    /// Module state. The 'inherited' value is write-only.
    #[serde(rename = "state", skip_serializing_if = "Option::is_none")]
    pub state: Option<State>,
    #[serde(rename = "moduleStatus", skip_serializing_if = "Option::is_none")]
    pub module_status: Option<Box<crate::models::ComputerModuleStatus>>,
    /// ID of the Global Stateful Configuration.
    #[serde(
        rename = "globalStatefulConfigurationID",
        skip_serializing_if = "Option::is_none"
    )]
    pub global_stateful_configuration_id: Option<i32>,
    #[serde(
        rename = "statefulConfigurationAssignments",
        skip_serializing_if = "Option::is_none"
    )]
    pub stateful_configuration_assignments:
        Option<Box<crate::models::StatefulConfigurationAssignments>>,
    /// IDs of the assigned firewall rules.
    #[serde(rename = "ruleIDs", skip_serializing_if = "Option::is_none")]
    pub rule_ids: Option<Vec<i32>>,
}

impl FirewallComputerExtension {
    /// Computer-level configuration for the Firewall module. Null for tenants for whom Firewall is hidden.
    pub fn new() -> FirewallComputerExtension {
        FirewallComputerExtension {
            state: None,
            module_status: None,
            global_stateful_configuration_id: None,
            stateful_configuration_assignments: None,
            rule_ids: None,
        }
    }
}

/// Module state. The 'inherited' value is write-only.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum State {
    #[serde(rename = "inherited")]
    Inherited,
    #[serde(rename = "on")]
    On,
    #[serde(rename = "off")]
    Off,
}
