/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntrusionPreventionRules {
    #[serde(
        rename = "intrusionPreventionRules",
        skip_serializing_if = "Option::is_none"
    )]
    pub intrusion_prevention_rules: Option<Vec<crate::models::IntrusionPreventionRule>>,
}

impl IntrusionPreventionRules {
    pub fn new() -> IntrusionPreventionRules {
        IntrusionPreventionRules {
            intrusion_prevention_rules: None,
        }
    }
}
