/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// IntrusionPreventionRuleRights : Intrusion prevention rule right details.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct IntrusionPreventionRuleRights {
    /// Right to create new intrusion prevention rules.
    #[serde(rename = "canCreateNewIntrusionPreventionRules", skip_serializing_if = "Option::is_none")]
    pub can_create_new_intrusion_prevention_rules: Option<bool>,
    /// Right to delete intrusion prevention rules.
    #[serde(rename = "canDeleteIntrusionPreventionRules", skip_serializing_if = "Option::is_none")]
    pub can_delete_intrusion_prevention_rules: Option<bool>,
    /// Right to edit intrusion prevention rule properties.
    #[serde(rename = "canEditIntrusionPreventionRuleProperties", skip_serializing_if = "Option::is_none")]
    pub can_edit_intrusion_prevention_rule_properties: Option<bool>,
}

impl IntrusionPreventionRuleRights {
    /// Intrusion prevention rule right details.
    pub fn new() -> IntrusionPreventionRuleRights {
        IntrusionPreventionRuleRights {
            can_create_new_intrusion_prevention_rules: None,
            can_delete_intrusion_prevention_rules: None,
            can_edit_intrusion_prevention_rule_properties: None,
        }
    }
}


