/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// SoftwareChangeReview : Software change review details.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SoftwareChangeReview {
    /// List of software change IDs.
    #[serde(rename = "softwareChangeIDs", skip_serializing_if = "Option::is_none")]
    pub software_change_ids: Option<Vec<i64>>,
    /// Action to perform on the software changes.
    #[serde(rename = "action", skip_serializing_if = "Option::is_none")]
    pub action: Option<Action>,
    /// Results of software changes.
    #[serde(
        rename = "softwareChangeReviewResults",
        skip_serializing_if = "Option::is_none"
    )]
    pub software_change_review_results: Option<Vec<crate::models::SoftwareChangeReviewResult>>,
}

impl SoftwareChangeReview {
    /// Software change review details.
    pub fn new() -> SoftwareChangeReview {
        SoftwareChangeReview {
            software_change_ids: None,
            action: None,
            software_change_review_results: None,
        }
    }
}

/// Action to perform on the software changes.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Action {
    #[serde(rename = "allow")]
    Allow,
    #[serde(rename = "block")]
    Block,
}
