/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// StatefulConfigurationRights : Stateful configuration right details.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct StatefulConfigurationRights {
    /// Right to create new stateful configurations.
    #[serde(
        rename = "canCreateNewStatefulConfigurations",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_create_new_stateful_configurations: Option<bool>,
    /// Right to delete stateful configurations.
    #[serde(
        rename = "canDeleteStatefulConfigurations",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_delete_stateful_configurations: Option<bool>,
    /// Right to edit stateful configuration properties.
    #[serde(
        rename = "canEditStatefulConfigurationProperties",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_edit_stateful_configuration_properties: Option<bool>,
}

impl StatefulConfigurationRights {
    /// Stateful configuration right details.
    pub fn new() -> StatefulConfigurationRights {
        StatefulConfigurationRights {
            can_create_new_stateful_configurations: None,
            can_delete_stateful_configurations: None,
            can_edit_stateful_configuration_properties: None,
        }
    }
}
