/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// TagFilter : Details for a tag filter. For reports that contain event data, identifies the tags of the events to include in the report.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TagFilter {
    /// Type of tag filter.
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub _type: Option<Type>,
    /// Tags to be used when type is: specific-tags
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl TagFilter {
    /// Details for a tag filter. For reports that contain event data, identifies the tags of the events to include in the report.
    pub fn new() -> TagFilter {
        TagFilter {
            _type: None,
            tags: None,
        }
    }
}

/// Type of tag filter.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "all")]
    All,
    #[serde(rename = "untagged")]
    Untagged,
    #[serde(rename = "specific-tags")]
    SpecificTags,
}
