/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct TrustRules {
    #[serde(rename = "trustRuleCount", skip_serializing_if = "Option::is_none")]
    pub trust_rule_count: Option<i32>,
    #[serde(
        rename = "applicationControlTrustRules",
        skip_serializing_if = "Option::is_none"
    )]
    pub application_control_trust_rules: Option<Vec<crate::models::ApplicationControlTrustRule>>,
}

impl TrustRules {
    pub fn new() -> TrustRules {
        TrustRules {
            trust_rule_count: None,
            application_control_trust_rules: None,
        }
    }
}
