/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 *
 * Generated by: https://openapi-generator.tech
 */

/// UpdateRights : Update right details.

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdateRights {
    /// Right to import software.
    #[serde(rename = "canImportSoftware", skip_serializing_if = "Option::is_none")]
    pub can_import_software: Option<bool>,
    /// Right to delete software.
    #[serde(rename = "canDeleteSoftware", skip_serializing_if = "Option::is_none")]
    pub can_delete_software: Option<bool>,
    /// Right to edit software properties.
    #[serde(
        rename = "canEditSoftwareProperties",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_edit_software_properties: Option<bool>,
    /// Right to import and apply rule updates.
    #[serde(
        rename = "canImportRuleUpdates",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_import_rule_updates: Option<bool>,
    /// Right to delete rule updates.
    #[serde(
        rename = "canDeleteRuleUpdates",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_delete_rule_updates: Option<bool>,
    /// Right to view rule updates.
    #[serde(rename = "canViewRuleUpdates", skip_serializing_if = "Option::is_none")]
    pub can_view_rule_updates: Option<bool>,
}

impl UpdateRights {
    /// Update right details.
    pub fn new() -> UpdateRights {
        UpdateRights {
            can_import_software: None,
            can_delete_software: None,
            can_edit_software_properties: None,
            can_import_rule_updates: None,
            can_delete_rule_updates: None,
            can_view_rule_updates: None,
        }
    }
}
