/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VCenterConnector : Everything about VCenter connector.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VCenterConnector {
    /// ID number of the vCenter connector.
    #[serde(rename = "id", skip_serializing_if = "Option::is_none")]
    pub id: Option<i32>,
    #[serde(rename = "vCenter", skip_serializing_if = "Option::is_none")]
    pub v_center: Option<Box<crate::models::VCenterInfo>>,
}

impl VCenterConnector {
    /// Everything about VCenter connector.
    pub fn new() -> VCenterConnector {
        VCenterConnector {
            id: None,
            v_center: None,
        }
    }
}


