/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// VirtualMachineSecurityGroup : AWS Security Group for EC2 instances.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct VirtualMachineSecurityGroup {
    /// Name of the Security Group.
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// ID of the Security Group.
    #[serde(rename = "ID", skip_serializing_if = "Option::is_none")]
    pub ID: Option<String>,
}

impl VirtualMachineSecurityGroup {
    /// AWS Security Group for EC2 instances.
    pub fn new() -> VirtualMachineSecurityGroup {
        VirtualMachineSecurityGroup {
            name: None,
            ID: None,
        }
    }
}


