/*
 * Trend Micro Workload Security API
 *
 * Copyright 2018 - 2022 Trend Micro Incorporated.<br/>Get protected, stay secured, and keep informed with Trend Micro Workload Security's new RESTful API. Access system data and manage security configurations to automate your security workflows and integrate Workload Security into your CI/CD pipeline.  # Authentication  <!-- ReDoc-Inject: <security-definitions> -->
 *
 * The version of the OpenAPI document: 50.0.827
 * 
 * Generated by: https://openapi-generator.tech
 */

/// WeeklyScheduleParameters : Details for the weekly schedule of a scheduled task.



#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct WeeklyScheduleParameters {
    /// Date/Time when the task should run.
    #[serde(rename = "startTime", skip_serializing_if = "Option::is_none")]
    pub start_time: Option<i64>,
    /// Number of weeks between recurrences.
    #[serde(rename = "interval", skip_serializing_if = "Option::is_none")]
    pub interval: Option<i32>,
    /// Days of the week when the scheduled task will run.
    #[serde(rename = "days", skip_serializing_if = "Option::is_none")]
    pub days: Option<Vec<Days>>,
}

impl WeeklyScheduleParameters {
    /// Details for the weekly schedule of a scheduled task.
    pub fn new() -> WeeklyScheduleParameters {
        WeeklyScheduleParameters {
            start_time: None,
            interval: None,
            days: None,
        }
    }
}

/// Days of the week when the scheduled task will run.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum Days {
    #[serde(rename = "sunday")]
    Sunday,
    #[serde(rename = "monday")]
    Monday,
    #[serde(rename = "tuesday")]
    Tuesday,
    #[serde(rename = "wednesday")]
    Wednesday,
    #[serde(rename = "thursday")]
    Thursday,
    #[serde(rename = "friday")]
    Friday,
    #[serde(rename = "saturday")]
    Saturday,
}

